# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UXgyPl9bgmqvToGQ9UHtll1hgpHmiaha
"""

import numpy as np
import matplotlib.pyplot as plt
# Here we are making our own data for hours studied vs marks scored
np.random.seed(42)
hours_studied = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
marks_scored = np.array([35, 40, 50, 55, 60, 65, 72, 78, 85, 92])
X = hours_studied
y = marks_scored
x_mean = np.mean(X)
y_mean = np.mean(y)
numerator = np.sum((X - x_mean) * (y - y_mean))
denominator = np.sum((X - x_mean) ** 2)
m = numerator / denominator
b = y_mean - m * x_mean
print("Slope (m):", m)
print("Intercept (b):", b)
y_pred = m * X + b
print("Predicted values:", y_pred)
mse = np.mean((y - y_pred) ** 2)
print("Mean Squared Error:", mse)
plt.scatter(X, y, color="blue", label="Actual Data")
plt.plot(X, y_pred, color="red", label="Regression Line")
plt.xlabel("Hours Studied")
plt.ylabel("Marks Scored")
plt.title("Linear Regression From Scratch")
plt.legend()
plt.savefig("linear_regression_output.png")
plt.show()